// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://gvidvuqdunlwuxvqkoca.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6Imd2aWR2dXFkdW5sd3V4dnFrb2NhIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQwOTAyODMsImV4cCI6MjA1OTY2NjI4M30.i5oeeLIzBW85E_SUP0He-dYbGMa2l0wCrQtzvbn8OmE";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);